parameters:
    yasiekz_router.router.class: Yasiekz\RouterBundle\Service\Router
    yasiekz_router.strategy.cms.class: Yasiekz\RouterBundle\Strategy\CmsStrategy
    yasiekz_router.strategy.front.class: Yasiekz\RouterBundle\Strategy\FrontStrategy

services:
    yasiekz_router.router.default:
        class: %yasiekz_router.router.class%
        arguments:
            - @service_container
            - %router.resource%
            - { debug: %kernel.debug%, generator_class: %router.options.generator_class%, generator_base_class: %router.options.generator_base_class%, generator_dumper_class: %router.options.generator_dumper_class%, generator_cache_class: %router.options.generator.cache_class%, matcher_class: %router.options.matcher_class%, matcher_base_class: %router.options.matcher_base_class%, matcher_dumper_class: %router.options.matcher_dumper_class%, matcher_cache_class: %router.options.matcher.cache_class% }
            - @?router.request_context]
    
    router: @yasiekz_router.router.default

    yasiekz_router.router.strategy.cms:
        class: %yasiekz_router.strategy.cms.class%

    yasiekz_router.router.strategy.front:
        class: %yasiekz_router.strategy.front.class%
